spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&serverTimezone=UTC
    username: root
    password: 133322
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.chat.**.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
server:
  port: 8089
